/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"stm_f103rb.h"
#include"api.h"
#include"stm32f103xb.h"


int main(void)
{

	BuildinLED_Blink();
	__enable_irq();
	/* Loop forever */
	for(;;)
	{
		BuildinLED_Blink();

	}



}
//void EXTI15_10_IRQHandler(void)
//{
//	 if (EXTI->PR & EXTI_PR_PR13)
//	    {
//	        // Clear the EXTI line 13 pending bit
//	        EXTI->PR |= EXTI_PR_PR13;
//
//	        // Your interrupt handling code here
//	        // ...
//	    	/* Togle GPIOA5*/
//	        GPIOA->ODR ^= (1<<5);
////	    	*GPIOA_ODR ^= (1<<5);
//	    	Delay(1000000);
//	    }
//
//}
