/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"stm_f103rb.h"
#include"api.h"
#include"stm32f103xb.h"



uint64_t Counter = 0;
uint16_t ADC_Data = 0;
int main(void)
{
	GPIO_Config();
	ADC_Config();

	while(1)
	{
		ADC_Data = ADC_ReadValue();
		Counter++;
	}

}

